# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:



jobs:
  test-node:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - name: Set node version
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - name: log versions
        run: |
          node --version
          npm -v

      - name: Reuse npm cache folder
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: |
            ~/.npm
            ./node_modules
          key: ${{ runner.os }}-npm-core-x4-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-core-x4-

      - name: 'Create env file'
        run: |
          touch .env
          echo RXDB_PREMIUM=${{ secrets.RXDB_PREMIUM }} >> .env
          cat .env

      - run: npm install

      - run: npm run test:node

      # - run: npm run test:browser
